name: Compile and Upload

on:
  workflow_dispatch:
    inputs:
      path:
        description: 'File path'
        required: true
        type: string

env:
  IMAGE_NAME: ghcr.io/mo-mo-666/latex-ubuntu:2022
  FILE_PATH: ${{ github.event.inputs.path }}

jobs:
  compile:
    name: Compile and Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Pull Docker image
        run: docker pull $IMAGE_NAME

      - name: Compile LaTeX document
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            $IMAGE_NAME \
            sh -c "latexmk -pdf -interaction=nonstopmode -file-line-error $FILE_PATH"

      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: compiled
          path: |
            ${{ github.workspace }}/$(basename $FILE_PATH .tex).pdf
            # ${{ github.workspace }}/$(basename $FILE_PATH .tex).aux
            ${{ github.workspace }}/$(basename $FILE_PATH .tex).log
            # ${{ github.workspace }}/$(basename $FILE_PATH .tex).out
            # ${{ github.workspace }}/$(basename $FILE_PATH .tex).toc
            # ${{ github.workspace }}/$(basename $FILE_PATH .tex).fls
            # ${{ github.workspace }}/$(basename $FILE_PATH .tex).fdb_latexmk
